language: node_js

node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

script:
  - yarn lint && yarn test --coverage && yarn build

after_success:
  - npx codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn run semantic-release

branches:
  only:
    - master
